/**
 * Daily puzzle scheduling.
 *
 * The order clips were uploaded is the schedule: day 1 is the first clip, day N
 * is the Nth. `src/data/schedule.json` is generated by scripts/build-schedule.mjs
 * and is append-only, so adding a clip defines the next open day and can never
 * change one that has already been played.
 *
 * Nothing here derives the answer from the current pool size. That was the old
 * behaviour, and it meant adding a single clip reshuffled weeks of answers.
 */

import schedule from '../data/schedule.json'
import { PLAYERS_BY_ID } from '../data/players.js'

export const MAX_GUESSES = 5
export const MAX_STAGE = 4

/** Local midnight, so day maths ignores clock time. */
function startOfDay(date) {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate())
}

/** Stable `YYYY-MM-DD` key in local time. */
export function dateKey(date = new Date()) {
  const d = startOfDay(date)
  const pad = (n) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
}

/**
 * Whole days between two `YYYY-MM-DD` keys.
 *
 * The calendar fields are reprojected onto UTC before subtracting. Differencing
 * local midnights directly is off by an hour across a daylight-saving boundary,
 * which floors to the *previous* day and hands out the same puzzle twice.
 */
export function daysBetween(fromKey, toKey) {
  const utc = (key) => {
    const [y, m, d] = key.split('-').map(Number)
    return Date.UTC(y, m - 1, d)
  }
  return Math.round((utc(toKey) - utc(fromKey)) / 86400000)
}

/** Puzzle number for a date. Day 1 is the epoch; clamped so it never goes below 1. */
export function puzzleNumberFor(date = new Date()) {
  return Math.max(1, daysBetween(schedule.epoch, dateKey(date)) + 1)
}

/**
 * Resolve a scheduled id to a player.
 *
 * Falls back to the first id that does resolve rather than returning undefined:
 * SilhouetteReveal and GuessGrid both dereference `puzzle.player` without
 * guarding, so a missing id would blank the page rather than degrade.
 */
function resolvePlayer(id) {
  const player = PLAYERS_BY_ID[id]
  if (player) return player
  for (const candidate of schedule.order) {
    const fallback = PLAYERS_BY_ID[candidate]
    if (fallback) return fallback
  }
  return null
}

/**
 * Today's puzzle, or any given date's.
 *
 * Past the end of the schedule the answer wraps around the existing order, so a
 * missed upload shows a repeat rather than an empty puzzle. The next generator
 * run freezes whatever was shown into the schedule permanently.
 */
export function getPuzzle(date = new Date()) {
  const number = puzzleNumberFor(date)
  const { order } = schedule
  const index = number - 1
  const id = index < order.length ? order[index] : order[index % order.length]

  return {
    number,
    dateKey: dateKey(date),
    player: resolvePlayer(id),
    /** True once the schedule has run out and answers are repeating. */
    isRepeat: index >= order.length,
  }
}

/** Milliseconds until the next local midnight. */
export function msUntilNextPuzzle(now = new Date()) {
  const next = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1)
  return next - now
}

/**
 * Reveal stage for a number of guesses used. Stage 1 is the bare silhouette;
 * each wrong guess sharpens it, capping before the final guess so the last
 * attempt is never a giveaway.
 */
export function stageForGuesses(guessCount) {
  return Math.min(MAX_STAGE - 1, guessCount + 1)
}
